.TH "md_README" 3 "Lundi 3 Janvier 2022" "IMA'GALAXY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- IMA'GALAXY 

.PP
Projet de synthèse d'image, programmation, et architecture logicielle lors du semestre 3 à l'IMAC, inspiré du jeu Temple Run\&.
.SS "<strong>Par Clément Bourhis, Sirine Bradai, Sacha Chouvin, et Estelle Thouvenin</strong>"
.SH "Librairies"
.PP
Pour pouvoir compiler correctement le projet, les librairies SDL, OpenGL, et GLEW sont nécessaires\&.
.SH "Compiler le projet"
.PP
Créer un dossier build à l'emplacement désiré 
.PP
.nf
mkdir build
cd build

.fi
.PP
.PP
Build le projet depuis le dossier build, penser à mettre le chemin relatif vers le dossier du projet 
.PP
.nf
cmake [chemin-relatif-vers-la-racine-du-dossier-du-projet]

.fi
.PP
.PP
Compiler le projet depuis le dossier build 
.PP
.nf
make

.fi
.PP
.PP
Exécuter le jeu 
.PP
.nf
\&./Test_Meshs/Test_Meshs_Test_GameManager

.fi
.PP
.SH "Commandes"
.PP
.SS "<em><strong>Déplacements</strong></em>"
.IP "\(bu" 2
\fBQ\fP : tourner à gauche
.IP "\(bu" 2
\fBD\fP : tourner à droite
.IP "\(bu" 2
\fBZ\fP : sauter
.PP
.SS "<em><strong>Caméra</strong></em>"
.IP "\(bu" 2
\fBclic gauche\fP : tourner la caméra
.IP "\(bu" 2
\fBflèche haut\fP : avancer la caméra *(depuis la vue centrée sur l'explorateur)*
.IP "\(bu" 2
\fBflèche bas\fP : reculer la caméra *(depuis la vue centrée sur l'explorateur)*
.IP "\(bu" 2
\fBmolette souris\fP : avancer ou reculer la caméra *(depuis la vue centrée sur l'explorateur)*
.IP "\(bu" 2
\fBC\fP : changer le type de caméra *(caméra centrée sur l'explorateur ou voir à travers les yeux de l’explorateur)*
.IP "\(bu" 2
\fBL\fP : bloquer la caméra
.PP
.SS "<em><strong>Divers</strong></em>"
.IP "\(bu" 2
\fBU\fP : sauvegarder la partie en cours
.IP "\(bu" 2
\fBSuppr\fP : depuis le menu, permet de fermer l'application
.IP "\(bu" 2
\fBREPLAY\fP : lancer la partie sauvegardée
.PP
.SH "Documentation Doxygen"
.PP
Pour plus d'informations, ouvrir la documentation Doxygen dans un navigateur : \fCDocHTML/index\&.html\fP 
